### PR TITLE
Prepare for new `http2` architecture

### PR DESCRIPTION
**Pull request by edsko**
See

* https://github.com/kazu-yamamoto/http2/issues/127
* https://github.com/kazu-yamamoto/http2/pull/130

### CODE REVIEW

**Comment by edsko** [comment]
The tests currently fail.

**Comment by edsko** [comment]
| client \ server | old http2 | new http2 |
| -- | -- | -- |
| old http2 | ✅ | ❌ |
| new http2 |✅ |❌ | 

So it seems something goes wrong server-side.

**Comment by edsko** [comment]
Server running old `http2` up to (including) the black marked packet, server running new `http2` after that (client running old `http2`):

image

The client can connect, the server even responds with HTTP 200 and the gRPC headers, but then the client is left waiting for the rest of the response.

**Comment by kazu-yamamoto** [comment]
`waitForOutbound` calls `waitForNormalThreadTermination`.
Which thread does waitForNormalThreadTermination` wait for?

**Comment by kazu-yamamoto** [comment]
I guess that the thread forked at https://github.com/well-typed/grapesy/blob/main/util/Network/GRPC/Util/Session/Server.hs#L72 does not terminate since `response` terminates when the stream is finished in the new architecture.

**Comment by edsko** [comment]
Locally tested 1000 `withoutExceptions` and 10,000 `withExceptions` tests, all passed :heavy_check_mark:

**Comment by edsko** [comment]
Have opened #190 to track https://github.com/well-typed/grapesy/pull/184#issuecomment-2220525818 .

**Pull request merged**
